// content/drivers/source/includes/node-frameworks/meteor-vue/RestaurantList.vue
<script setup>
import Restaurant from '../components/Restaurant.vue';
import { subscribe, autorun } from 'vue-meteor-tracker';
import { RestaurantsCollection } from '../../api/restaurantsCollection';
import { useRoute, RouterLink } from 'vue-router';
import { computed } from 'vue';

const route = useRoute();

// Determines whether to show filtered results
const isFiltered = computed(() => route.path === '/browse');

// Subscribes to both publications to avoid switching issues
subscribe('restaurants');
subscribe('restaurants.filtered');

// Retrieves restaurants based on current route with client-side filtering as backup
const restaurants = autorun(() => {
  let docs;
  
  if (isFiltered.value) {
    docs = RestaurantsCollection.find({
      borough: 'Queens',
      name: { $regex: 'Moon', $options: 'i' }
    }).fetch();
    console.log('Filtered restaurants found:', docs.length);
  } else {
    docs = RestaurantsCollection.find({}, { limit: 200 }).fetch();
    console.log('All restaurants found:', docs.length);
  }
  
  return docs;
}).result;

// Determines the title based on the route
const getTitle = computed(() => {
  return isFiltered.value 
    ? 'Filtered Restaurants (Queens, containing "Moon")' 
    : 'All Restaurants';
});
</script>

<template>
  <div class="container mx-auto px-4">
    <!-- Navigation -->
    <nav class="flex justify-between items-center mb-6 p-4 bg-white shadow rounded">
      <div class="flex space-x-4">
        <RouterLink 
          to="/" 
          class="px-4 py-2 text-blue-600 hover:bg-blue-50 rounded transition-colors"
          :class="{ 'bg-blue-100 font-semibold': !isFiltered }"
        >
          All Restaurants
        </RouterLink>
        <RouterLink 
          to="/browse" 
          class="px-4 py-2 text-blue-600 hover:bg-blue-50 rounded transition-colors"
          :class="{ 'bg-blue-100 font-semibold': isFiltered }"
        >
          Browse Filtered
        </RouterLink>
      </div>
    </nav>

    <!-- Header -->
    <header class="mb-6">
      <h1 class="text-4xl font-bold text-gray-800 my-4">Restaurant Directory</h1>
      <h3 class="text-lg font-semibold text-gray-600">{{ getTitle }}</h3>
    </header>

    <!-- Restaurant Table -->
    <div class="border rounded-lg overflow-hidden shadow">
      <div class="relative w-full overflow-auto">
        <table class="w-full text-sm">
          <thead class="bg-gray-100 border-b-2 border-gray-300">
            <tr class="border-b-2 border-gray-400">
              <th class="h-14 px-4 text-left align-middle font-bold text-gray-900 text-base tracking-wide">
                Name
              </th>
              <th class="h-14 px-4 text-left align-middle font-bold text-gray-900 text-base tracking-wide">
                Borough
              </th>
              <th class="h-14 px-4 text-left align-middle font-bold text-gray-900 text-base tracking-wide">
                Cuisine
              </th>
            </tr>
          </thead>
          <tbody>
            <Restaurant 
              v-for="restaurant in restaurants" 
              :key="restaurant._id" 
              :restaurant="restaurant" 
            />
          </tbody>
        </table>
        
        <!-- Empty state -->
        <div v-if="restaurants.length === 0" class="p-8 text-center text-gray-500">
          <p>No restaurants found. Ensure that your connection URI is correct and includes the sample_restaurants database name.</p>
          <p v-if="isFiltered" class="text-sm mt-2">
            Try the "All Restaurants" tab to see all available restaurants.
          </p>
        </div>
      </div>
    </div>

    <!-- Restaurant count -->
    <div class="mt-4 text-sm text-gray-600">
      Showing {{ restaurants.length }} restaurant{{ restaurants.length !== 1 ? 's' : '' }}
    </div>
  </div>
</template>

// content/drivers/source/includes/node-frameworks/react/RestaurantList.jsx
import { useEffect, useState } from "react";
import { useLocation } from "react-router-dom";

const Restaurant = (props) => (
  <tr className="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
    <td className="p-4 align-middle [&:has([role=checkbox])]:pr-0">
      {props.restaurant.name}
    </td>
    <td className="p-4 align-middle [&:has([role=checkbox])]:pr-0">
      {props.restaurant.borough}
    </td>
    <td className="p-4 align-middle [&:has([role=checkbox])]:pr-0">
      {props.restaurant.cuisine}
    </td>
  </tr>
);

export default function RestaurantList() {
  const [restaurants, setRestaurants] = useState([]);
  const location = useLocation();

  // Fetches the restaurants from the database
  useEffect(() => {
    async function getRestaurants() {
      // Determines which endpoint to call based on current route
      const endpoint =
        location.pathname === "/browse"
          ? "http://localhost:5050/restaurant/browse"
          : "http://localhost:5050/restaurant/";

      const response = await fetch(endpoint);
      if (!response.ok) {
        const message = `An error occurred: ${response.statusText}`;
        console.error(message);
        return;
      }
      const restaurants = await response.json();
      setRestaurants(restaurants);
    }
    getRestaurants();
    return;
  }, [location.pathname]);

  // Maps each restaurant on the table
  function restaurantList() {
    return restaurants.map((restaurant) => {
      return <Restaurant restaurant={restaurant} key={restaurant._id} />;
    });
  }

  // Retrieves the dynamic title based on current route
  const getTitle = () => {
    return location.pathname === "/browse"
      ? 'Filtered Restaurants (Queens, containing "Moon")'
      : "All Restaurants";
  };

  // Displays the restaurants table
  return (
    <>
      <h3 className="text-lg font-semibold p-4">{getTitle()}</h3>
      <div className="border rounded-lg overflow-hidden">
        <div className="relative w-full overflow-auto">
          <table className="w-full caption-bottom text-sm">
            <thead className="[&_tr]:border-b">
              <tr className="border-b transition-colors hover:bg-muted/50 data-[state=selected]:bg-muted">
                <th className="h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0">
                  Name
                </th>
                <th className="h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0">
                  Borough
                </th>
                <th className="h-12 px-4 text-left align-middle font-medium text-muted-foreground [&:has([role=checkbox])]:pr-0">
                  Cuisine
                </th>
              </tr>
            </thead>
            <tbody className="[&_tr:last-child]:border-0">
              {restaurantList()}
            </tbody>
          </table>
        </div>
      </div>
    </>
  );
}
